title: Venkata Prasath
logo: /assets/img/VP.jpeg
description: Senior Software Engineering Leader with a Healthcare Background, Driving Strategic Product Development Efforts & Leading Top-Performing Teams to Deliver Multi-Million-Dollar Revenue Acceleration
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
